apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv-re
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local
  hostPath:
    path: /tmp/redmine/date
