apiVersion: v1
kind: Secret
metadata:
  name: my-secret-re
type: Opaque
data:
  REDMINE_DB_USERNAME: dGVzdHVzZXIK
  REDMINE_DB_PASSWORD: dGVzdHBhc3N3b3JkCg==
  REDMINE_SECRET_KEY_BASE: c3VwZXJzZWNyZXRrZXkK